# Generated by Django 3.0.3 on 2022-02-18 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_appuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('sent', 'sent'), ('accepted', 'accepted')], max_length=10)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='social.AppUser')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='social.AppUser')),
            ],
        ),
    ]
