# Generated by Django 3.0.3 on 2022-02-28 04:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0004_auto_20220222_1643'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='StatusPost',
        ),
        migrations.AlterModelOptions(
            name='appuser',
            options={'ordering': ['user']},
        ),
        migrations.AlterModelOptions(
            name='friendsrelationship',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='statuspost',
            options={'ordering': ['-created']},
        ),
    ]
